repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      args: ["-l 100"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-added-large-files
    - id: mixed-line-ending
  # flake8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: [--config, setup.cfg]
        additional_dependencies: [
          flake8-docstrings,
          flake8-bugbear,
          flake8-pytest,
          pandas-vet
        ]
  # isort
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
    - id: seed-isort-config
      args: [--application-directories, flask/]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    - id: isort
  # Shellcheck
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
    - id: shell-lint
      args: [--format=json]
  # By default, do not commit notebook contents. Skip with SKIP=nbstripout
  - repo: https://github.com/kynan/nbstripout
    rev: master
    hooks:
      - id: nbstripout
        files: ".ipynb"
