name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: set PY
      run: echo "::set-env name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    # Pin to specific commit as we're injecting a token into the repository and tags *could* be changed.
    # This is `pre-commit/action@v1.0.1`
    - uses: pre-commit/action@9e7a37e7cb48990ef82a6fd8cef13e86bdfc2497
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
