name: test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Cache virtualenv
        uses: actions/cache@v1
        id: cache-pip
        with:
          path: venv
          key: venv-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies in a venv
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install --progress-bar=off -r requirements.txt
      - name: Run tests
        run: |
          . venv/bin/activate
          make test
